### ISSUE TITLE
 BOM Structure to Excel .XLSX Export the error

### ISSUE THREAD

**Issue by hermitguo** [OCA/manufacture-reporting#45] opened 2018-07-24 02:45 UTC
I installed it in the container.
My environment: centos7.4 + docker18.05 + odoo10 docker, I have the installation pip install pyeval.
but there was an error :  Uncaught ReferenceError:pyeval is not defined.

why?

**Comment by HviorForgeFlow** [comment] 2018-07-26 16:15
Hi @eremiter could you add full error content? I can't reproduce your error neither figure out why

**Comment by hermitguo** [comment] 2018-08-25 15:12
Hi, hveficent<mailto:notifications@github.com>,
sorry, busy recently.

  *   I solved the problem,https://stackoverflow.com/questions/44720758/uncaught-referenceerror-pyeval-is-not-defined


  *   I hope it's helpful

  *

________________________________
hermit

**Comment by MiquelRForgeFlow** [comment] 2018-08-27 10:19
Then, you should close the issue :)

**Closed as completed** 2018-08-28 15:34 UTC
